[project]
name = "random-barcrawl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.5",
    "numpy>=2.3.4",
    "pulp>=3.3.0",
    "pydantic>=2.12.5",
]
